//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdProgress
    {
        public int Id { get; set; }
        public int vendorId { get; set; }
        public int AdId { get; set; }
        public string bidType { get; set; }
        public string cost { get; set; }
        public string userPartialName { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
