//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCategory
    {
        public AppCategory()
        {
            this.SubCategories = new HashSet<SubCategory>();
            this.UserInterests = new HashSet<UserInterest>();
            this.VendorInterests = new HashSet<VendorInterest>();
        }
    
        public int Id { get; set; }
        public string categoryName { get; set; }
        public string categoryType { get; set; }
        public string iconName { get; set; }
        public string iconMarkerName { get; set; }
        public string color { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual ICollection<SubCategory> SubCategories { get; set; }
        public virtual ICollection<UserInterest> UserInterests { get; set; }
        public virtual ICollection<VendorInterest> VendorInterests { get; set; }
    }
}
