//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.AdInfoes = new HashSet<AdInfo>();
        }
    
        public int Id { get; set; }
        public string word { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual ICollection<AdInfo> AdInfoes { get; set; }
    }
}
