//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qlumi_testEntities1 : DbContext
    {
        public qlumi_testEntities1()
            : base("name=qlumi_testEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdInfo> AdInfoes { get; set; }
        public DbSet<admin> admins { get; set; }
        public DbSet<AdType> AdTypes { get; set; }
        public DbSet<AppCategory> AppCategories { get; set; }
        public DbSet<BidType> BidTypes { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<ChatHistory> ChatHistories { get; set; }
        public DbSet<crawler> crawlers { get; set; }
        public DbSet<excludedWord> excludedWords { get; set; }
        public DbSet<gpsNote> gpsNotes { get; set; }
        public DbSet<includedWord> includedWords { get; set; }
        public DbSet<meetingNote> meetingNotes { get; set; }
        public DbSet<messageCount> messageCounts { get; set; }
        public DbSet<ProfileColor> ProfileColors { get; set; }
        public DbSet<SettingProfile> SettingProfiles { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<UserContact> UserContacts { get; set; }
        public DbSet<UserGpsNote> UserGpsNotes { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<UserInterest> UserInterests { get; set; }
        public DbSet<userLocation> userLocations { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<VendorInterest> VendorInterests { get; set; }
        public DbSet<VendorNote> VendorNotes { get; set; }
        public DbSet<VendorProfile> VendorProfiles { get; set; }
        public DbSet<AdProgress> AdProgresses { get; set; }
        public DbSet<BillingInfo> BillingInfoes { get; set; }
    }
}
