//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.AdInfoes = new HashSet<AdInfo>();
            this.UserInterests = new HashSet<UserInterest>();
            this.VendorInterests = new HashSet<VendorInterest>();
        }
    
        public int Id { get; set; }
        public int categoryId { get; set; }
        public string subCategoryName { get; set; }
        public string subCategoryType { get; set; }
        public string color { get; set; }
        public string iconName { get; set; }
        public string iconMarkerName { get; set; }
        public Nullable<int> isCustom { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual ICollection<AdInfo> AdInfoes { get; set; }
        public virtual AppCategory AppCategory { get; set; }
        public virtual ICollection<UserInterest> UserInterests { get; set; }
        public virtual ICollection<VendorInterest> VendorInterests { get; set; }
    }
}
