//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdInfo
    {
        public int Id { get; set; }
        public Nullable<int> vendorId { get; set; }
        public Nullable<int> adTypeId { get; set; }
        public Nullable<int> bidTypeId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> interestId { get; set; }
        public Nullable<int> isCustom { get; set; }
        public Nullable<int> isVisible { get; set; }
        public string customInterest { get; set; }
        public string dailyBudget { get; set; }
        public string couponUrl { get; set; }
        public string mapVideo { get; set; }
        public string mapImage { get; set; }
        public string sponsorFacts { get; set; }
        public string sponsorWebsite { get; set; }
        public string sponsorPhone { get; set; }
        public string sponorLogo { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string adTitle { get; set; }
        public string lati { get; set; }
        public string longi { get; set; }
        public string locationName { get; set; }
        public string costPerAction { get; set; }
        public string costPerConversion { get; set; }
    
        public virtual AdType AdType { get; set; }
        public virtual BidType BidType { get; set; }
        public virtual category category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
