//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingHistory
    {
        public int Id { get; set; }
        public int vendorId { get; set; }
        public string invoiceNo { get; set; }
        public string currency { get; set; }
        public string amount { get; set; }
        public Nullable<System.DateTime> billingMonth { get; set; }
        public Nullable<System.DateTime> paidAt { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
