//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class crawler
    {
        public int Id { get; set; }
        public string placeId { get; set; }
        public string placeWebsite { get; set; }
        public string deviceId { get; set; }
        public string deviceLati { get; set; }
        public string deviceLongi { get; set; }
        public string htmlData { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string googleData { get; set; }
    }
}
