//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.ChatHistories = new HashSet<ChatHistory>();
            this.ChatHistories1 = new HashSet<ChatHistory>();
            this.messageCounts = new HashSet<messageCount>();
            this.SettingProfiles = new HashSet<SettingProfile>();
            this.UserContacts = new HashSet<UserContact>();
            this.UserGpsNotes = new HashSet<UserGpsNote>();
            this.userLocations = new HashSet<userLocation>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string contactNumber { get; set; }
        public string profileImage { get; set; }
        public string unlock_code { get; set; }
        public string gcm_token { get; set; }
        public string requestOrigin { get; set; }
        public string app_version { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string qlumi_userId { get; set; }
        public string connectionId { get; set; }
        public string sessionId { get; set; }
        public string loginStatus { get; set; }
        public string notesInfo { get; set; }
    
        public virtual ICollection<ChatHistory> ChatHistories { get; set; }
        public virtual ICollection<ChatHistory> ChatHistories1 { get; set; }
        public virtual ICollection<messageCount> messageCounts { get; set; }
        public virtual ICollection<SettingProfile> SettingProfiles { get; set; }
        public virtual ICollection<UserContact> UserContacts { get; set; }
        public virtual ICollection<UserGpsNote> UserGpsNotes { get; set; }
        public virtual ICollection<userLocation> userLocations { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
