//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorNote
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string lati { get; set; }
        public string longi { get; set; }
        public Nullable<int> sender_userId { get; set; }
        public string sender_name { get; set; }
        public Nullable<int> deliveryStatus { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    }
}
