//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorProfile
    {
        public VendorProfile()
        {
            this.VendorInterests = new HashSet<VendorInterest>();
        }
    
        public int Id { get; set; }
        public int vendorId { get; set; }
        public string profileName { get; set; }
        public string color { get; set; }
        public Nullable<int> colorId { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<VendorInterest> VendorInterests { get; set; }
    }
}
